<?php


use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_menu().
 */
function drc_menu() {


  $items[(string) \Drupal::config('drc.settings')->get('path')] = array(
    'route_name' => 'path.content'
  );

  $items['admin/config/drc'] = array(
    'route_name' => 'drc.admin_settings'
  );

  return $items;
  
}

/**
 * Implements hook_help().
 */
function drc_help($route_name, RouteMatchInterface $route_match) {
  	
  	if($route_name === 'drc.admin_settings'){
  		$output = '<br>';
  		$output .= '<h4>' . t('Welcome to drc configuration management.') . '</h4>';
  		$output .= '<p>';
  		$output .= t('In this section, you have permission to change your <b>livechat</b> management system.');
  		$output .= t(' As for now, you\'re only permitted to configure your server address as well as the server port.');
      $output .= '<br>';
      $output .= t('If you\'re running a localserver, Rocket.Chat use <b>localhost:3000</b>, else only (http/https) protocols and (80/443) ports are allowed.');
  		$output .= '<br>';
  		$output .= '<br>';
  		$output .= '<small><i>' . t('please <u>note</u> that this is the alpha version of the Rocket.Chat livechat module, more updates will be available.') . '</i></small>';	
  		$output .= '</p>';
  		$output .= '<br>'; 		
  		return $output;
  	}

  }

/**
 * Implements hook_form_alter().
 */

function drc_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
	
	 if($form_id === 'drc.admin_settings'){
    // when LiveChatForm get invoked..
	}
	
}

