<?php


use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\rest\ResourceResponse;

/**
 * Implements hook_menu().
 */
function drockchat_menu() {

  $items['drockchat'] = array(
    'route_name' => 'drockchat.content'
  );

  $items['admin/config/drockchat'] = array(
    'route_name' => 'drockchat.admin_settings'
  );

  return $items;
  
}

/**
 * Implements hook_help().
 */
function drockchat_help($route_name, RouteMatchInterface $route_match) {
  	
  	if($route_name === 'drockchat.admin_settings'){
  		$output = '<br>';
  		$output .= '<h4>' . t('Welcome to drockchat configuration management.') . '</h4>';
  		$output .= '<p>';
  		$output .= t('In this section, you have permission to change your <b>livechat</b> management system.');
  		$output .= t(' As for now, you\'re only permitted to configure your server address as well as the server port.');
  		$output .= '<br>';
  		$output .= '<br>';
  		$output .= '<small><i>' . t('please <u>note</u> that this is the alpha version of the Rocket.Chat livechat module, more updates will be available. Thank You!') . '</i></small>';	
  		$output .= '</p>';
  		$output .= '<br>'; 		
  		return $output;
  	}

  }

/**
 * Implements hook_form_alter().
 */

function drockchat_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
	
	//  if($form_id === 'drockchat.admin_settings'){

 //      $test = new ResourceResponse([
 //              'json-key-1' => 'json-value-1',
 //              'json-key-2' => 'json-value-2'
 //            ]);

	//     $form['#attached']['library'][] = 'drockchat/json';

	//     $form['#attached']['drupalSettings']
	    
	//     // TODO: cast config->get('key') to JSON format  
	//     ['drockchat']['json']['server'] = // \Drupal::config('drockchat.settings')->get('server');
 //            $test->getResponseData();

	//     $form['#attached']['drupalSettings']
	//     ['drockchat']['json']['port'] = \Drupal::config('drockchat.settings')->get('port');

	//     return $form;
	// }
	
}
